# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingerservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), editable=False),
        ),
    ]
