# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingerservice', '0002_auto_20170724_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervall',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
