# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingerservice', '0003_auto_20170724_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='keyboard_layout',
            field=models.CharField(choices=[('DE', 'German'), ('EN', 'English')], default='DE', max_length=2),
        ),
    ]
