# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingerservice', '0005_auto_20170906_0915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intervall',
            new_name='Interval',
        ),
    ]
