# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingerservice', '0006_auto_20171011_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day',
            new_name='ComputerDay',
        ),
    ]
